[INCLUDES]

before = botsearch-common.conf

[Definition]

# Nginx Proxy Manager botsearch filter
# Detects bots searching for common vulnerable paths and files

# NPM access log format:
# [12/Aug/2026:04:37:58 +0000] 405 - POST http 155.248.230.163 "/" [Client 78.153.140.148] [Length 556] [Gzip -] "Mozilla/5.0..." "-"

failregex = ^\[.*?\\] 404 - .*? \"(GET|POST) /<block> .*?\" 404\\s -.*?\\[Client <HOST>\\]

ignoreregex =

datepattern = {^LN-BEG}%%ExY(?P<_sep>[-/.])%%m(?P=_sep)%%d[T ]%%H:%%M:%%S(?:[.,]%%f)?(?:\\s*%%z)?